version: '2.0'

services:
  web:
    image: phxchat1.0
    ports:
    - "8000:4000"
    volumes:
    - .:/app
    environment:
    - REDIS_PUBSUB_NODE_NAME=webapp_one
    - PHOENIX_REDIS_URI=redis://redis:6379
    - POSTGRES_TEST_DB_URL=postgresql://postgres:verysecurepassword@postgres/phx_chat_test
  bizzaro_web:
    image: phxchat1.0
    ports:
    - "8001:4000"
    volumes:
    - .:/app
    environment:
    - REDIS_PUBSUB_NODE_NAME=webapp_two
    - PHOENIX_REDIS_URI=redis://redis:6379
  postgres:
    image: postgres:12.2
    environment:
      - POSTGRES_PASSWORD=verysecurepassword
    volumes:
      - phx_chat_pg_data:/var/lib/postgresql/data
  redis:
    image: "redis:alpine"
  # TODO: Add Nginx?

# Created volume manually with docker volume create before using it here
volumes:
  phx_chat_pg_data:

#########
# Usage #
#########

# docker-compose up -d

# docker-compose down

# docker logs --follow phx_chat_web_1

# docker exec -it phx_chat_web_1 bash
