# phx_chat CircleCI configuration

version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1
  docker: circleci/docker@1.0.1
  kubernetes: circleci/kubernetes@0.11.0

executors:
  elixir-executor:
    docker:
      - image: circleci/elixir:1.9.4
        environment:
          POSTGRES_TEST_DB_URL: postgresql://postgres:verysecurepassword@localhost/phx_chat_test
          PHOENIX_REDIS_URI: redis://localhost:6379
      - image: circleci/postgres:12.2
        environment:
          POSTGRES_PASSWORD: verysecurepassword
          POSTGRES_USER: postgres
          POSTGRES_DB: phx_chat_test
      - image: circleci/redis:alpine
    working_directory: ~/repo
  # TODO ERIC remove if unused
  barebones-executor:
    docker:
      - image: cimg/base:2020.01
    working_directory: ~/repo

jobs:
  build-and-test:
    executor: elixir-executor
    steps:
      - checkout
      - run: mix local.hex --force && mix local.rebar --force
      - run: mix deps.get
      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success! Total attempts: $i && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1
      - run: mix test
      # Ensure compilation works and fail the build if there are any warnings
      - run: mix compile --warnings-as-errors
  deploy-to-heroku:
    executor: elixir-executor
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git
  build-docker-image:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - run:
          command: 'echo -n "we got this far, and we are in $(pwd)"'
      # TODO ERIC: Kind of a hack here; tag as latest then make k8s deploy the latest
      # ideally it will be tagged with the sha, then k8s will deploy this sha... maybe that's where I need helm?
      - docker/build:
          image: eqmvii/circle-build-test:latest
          dockerfile: ProdDockerfile
      - docker/push:
          image: eqmvii/circle-build-test:latest
  deploy-to-kubernetes:
    executor: barebones-executor
    steps:
      - checkout
      - run:
          command: 'echo "TODO ERIC remove testing k8s deployment step"'
      - kubernetes/install-kubectl
      - kubernetes/install-kubeconfig
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: kubernetes/deployment-phx-chat.yaml
          resource-name: phx-chat
          show-kubectl-command: true

workflows:
  version: 2

  build-test-deploy:
    jobs:
      - build-and-test:
          # TODO ERIC: remove this requires. Only used while testing docker process to speed things up.
          requires:
            - build-docker-image
      - build-docker-image
      - heroku-deploy-approval:
          filters:
            branches:
              only:
                - master
          type: approval
          requires:
            - build-and-test
      - kubernetes-deploy-approval:
          filters:
            branches:
              only:
                - master
          type: approval
          requires:
            - build-and-test
            - build-docker-image
      - deploy-to-heroku:
          filters:
            branches:
              only:
                - master
          requires:
            - heroku-deploy-approval
      - deploy-to-kubernetes:
          filters:
            branches:
              only:
                - master
          requires:
            - kubernetes-deploy-approval
