# phx_chat CircleCI configuration

version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1

executors:
  elixir-executor:
    docker:
      - image: circleci/elixir:1.9.4
        environment:
          POSTGRES_TEST_DB_URL: postgresql://postgres:verysecurepassword@localhost/phx_chat_test
          PHOENIX_REDIS_URI: redis://localhost:6379
      - image: circleci/postgres:12.2
        environment:
          POSTGRES_PASSWORD: verysecurepassword
          POSTGRES_USER: postgres
          POSTGRES_DB: phx_chat_test
      - image: circleci/redis:alpine
    working_directory: ~/repo

jobs:
  build-and-test:
    executor: elixir-executor
    steps:
      - checkout
      - run: mix local.hex --force && mix local.rebar --force
      - run: mix deps.get
      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success! Total attempts: $i && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1
      - run: mix test
      # Ensure compilation works and fail the build if there are any warnings
      - run: mix compile --warnings-as-errors
  deploy-to-heroku:
    executor: elixir-executor
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git

workflows:
  version: 2

  build-test-deploy:
    jobs:
      - build-and-test
      - heroku-deploy-approval:
          filters:
            branches:
              only:
                - master
          type: approval
          requires:
            - build-and-test
      - deploy-to-heroku:
          filters:
            branches:
              only:
                - master
          requires:
            - heroku-deploy-approval
