apiVersion: apps/v1
kind: Deployment
metadata:
  name: phx-chat
  labels:
    app: phx-chat
spec:
  selector:
    matchLabels:
      app:  phx-chat

  # sometimes using one or three replica to troubleshoot redis
  replicas: 3
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: phx-chat
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        # lol yes, typo, pivate not privae. Sigh.
        - image: eqmvii/pivate_phx_chat:8
          imagePullPolicy: Always
          name: phx-chat
          ports:
            - containerPort: 4000
          env:
            - name: PHOENIX_REDIS_URI
              value: redis://redis-pubsub:6379
            - name: KUBERNETES_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: heroku-db-url-secret
                  key: heroku-db-url
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: secret-key-base-secret
                  key: secret-key-base

###
### Helpful Commands
###

# Deploy & watch

# kubectl apply -f ./kubernetes/deployment-phx-chat-alpine.yaml --record && kubectl rollout status deployment phx-chat && kubectl get pods

