apiVersion: apps/v1
kind: Deployment
metadata:
  name: phx-chat
  labels:
    app: phx-chat
spec:
  selector:
    matchLabels:
      app:  phx-chat

  # sometimes using one or three replica to troubleshoot redis
  replicas: 3
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: phx-chat
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        # lol yes, typo, pivate not privae. Sigh.
        - name: server
          image: eqmvii/pivate_phx_chat:9
          imagePullPolicy: Always

          ports:
            - containerPort: 4000
          env:
            - name: PHOENIX_REDIS_URI
              value: redis://redis-pubsub:6379
            - name: KUBERNETES_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: cproxy-db-url-secret
                  key: cproxy-db-url
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: secret-key-base-secret
                  key: secret-key-base

        # sidecar container: proxy to gcp database
        - name: cproxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.16
          command: ["/cloud_sql_proxy"]
          args: ["-instances=peppy-archive-277221:us-east4:phx-chat-db=tcp:0.0.0.0:5432", "-credential_file=/config/peppy-archive-277221-6811d08aed21.json"]
          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true
      volumes:
        - name: config
          secret:
            secretName: cloud-proxy-json
###
### Helpful Commands
###

# Deploy & watch

# kubectl apply -f ./kubernetes/deployment-phx-chat.yaml --record && kubectl rollout status deployment phx-chat && kubectl get pods

