apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-test
  namespace: default
spec:
  containers:
  - name: ubuntu-test
    image: ubuntu:latest
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
