# testpod for a multi-container pod

apiVersion: v1
kind: Pod
metadata:
  name: cproxy
  labels:
    app: cproxy
spec:
  containers:
    # TODO ERIC: Update version here
    - image: gcr.io/cloudsql-docker/gce-proxy:1.17
      name: cproxy
      command: ["/cloud_sql_proxy"]
      args: ["-instances=peppy-archive-277221:us-east4:phx-chat-db=tcp:0.0.0.0:5433", "-credential_file=/config/peppy-archive-277221-6811d08aed21.json"]
      volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true

    - name: pg
      # using a pg container means we can bash in, then use psql to test the sidecar gcp connection
      image: postgres:12.2
      env:
        - name: POSTGRES_PASSWORD
          value: verysecurepassword
      ports:
        - containerPort: 5432

  volumes:
  - name: config
    secret:
      secretName: cloud-proxy-json

# TODO ERIC:
  # securityContext:
  #   # The default Cloud SQL proxy image is based on distroless, which
  #   # runs as the "nonroot" user (uid: 65534) by default.
  #   runAsNonRoot: true
