# A dummy ubuntu pod, to give bash access, play with secrets, etc.
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  labels:
    app: demo-pod
spec:
  containers:
    - image: ubuntu
      name: demo-pod
      command: ["sleep",  "1000000"]
