version: '2.0'

services:
  gcproxy:
    image: gcr.io/cloudsql-docker/gce-proxy:1.17
    ports:
    - "127.0.0.1:5433:5432"
    volumes:
    - .:/config
    command: "/cloud_sql_proxy -instances |INSTANCE NAME|=tcp:0.0.0.0:5432 -credential_file=/config/|CONFIG FILE NAME|.json"

# local connection (port 5433 because postgres reserves 5432)
# psql "host=127.0.0.1 port=5433 sslmode=disable dbname=phx_chat user=postgres"
